import streamlit as st
import pandas as pd
import numpy as np
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from datetime import datetime as dt

####################### PAGE CONFIGURATION #######################
st.set_page_config(page_title='Citi Bike NYC Strategy Dashboard', layout='wide')

####################### TITLE AND DESCRIPTION ####################
st.title("Citi Bike NYC Expansion Strategy Dashboard")
st.markdown("This dashboard provides data-driven insights to support Citi Bike's network expansion strategy in New York City. Analyze station demand, seasonal patterns, and geographic distribution to identify optimal locations for new stations.")

####################### IMPORT DATA ##############################
# Load preprocessed data
df_daily = pd.read_csv('outputs/daily_data.csv')
top20 = pd.read_csv('outputs/top20.csv')

####################### DEFINE CHARTS ############################

## Bar Chart - Top 20 Stations
st.header("Top 20 Most Popular Stations")
st.markdown("Identifying high-demand stations helps prioritize capacity expansion and bike redistribution efforts.")

fig = go.Figure(go.Bar(
    x=top20['value'],
    y=top20['start_station_name'],
    orientation='h',
    marker={'color': top20['value'], 'colorscale': 'Blues'}
))

fig.update_layout(
    title='Top 20 Most Popular Bike Stations in NYC',
    xaxis_title='Number of Trips',
    yaxis_title='Start Station',
    width=900,
    height=600
)

st.plotly_chart(fig, use_container_width=True)

## Dual-Axis Line Chart - Weather and Ridership
st.header("Seasonal Demand Patterns")
st.markdown("Temperature correlation reveals seasonal capacity planning needs and helps forecast demand fluctuations.")

fig_2 = make_subplots(specs=[[{"secondary_y": True}]])

# Add bike rides trace
fig_2.add_trace(
    go.Scatter(
        x=df_daily['date'],
        y=df_daily['bike_rides_daily'],
        name='Daily Bike Rides',
        marker={'color': 'blue'}
    ),
    secondary_y=False
)

# Add temperature trace
fig_2.add_trace(
    go.Scatter(
        x=df_daily['date'],
        y=df_daily['avgTemp'],
        name='Daily Temperature',
        marker={'color': 'red'}
    ),
    secondary_y=True
)

fig_2.update_layout(
    title='Daily Bike Rides and Temperature Correlation - 2022',
    xaxis_title='Date',
    height=600
)

fig_2.update_yaxes(title_text='Number of Bike Rides', secondary_y=False)
fig_2.update_yaxes(title_text='Temperature (°C)', secondary_y=True)

st.plotly_chart(fig_2, use_container_width=True)

####################### ADD MAP ##################################
st.header("Geographic Trip Distribution")
st.markdown("Interactive map shows popular routes and identifies network gaps for strategic expansion.")

# Path to HTML map file
path_to_html = "outputs/citibike_trips_map.html"

# Read file and keep in variable
try:
    with open(path_to_html, 'r') as f:
        html_data = f.read()
    
    # Display in dashboard
    st.components.v1.html(html_data, height=1000)
except FileNotFoundError:
    st.warning("Map file not found. Please ensure 'citibike_trips_map.html' is in the outputs folder.")
    st.info("The map can be regenerated by running the Exercise 2.5 notebook.")
